[package]
name = "bevy_woff"
version = "0.2.0"
edition = "2024"
description = "Bevy plugin for loading .woff and .woff2 web fonts as assets"
license = "MIT OR Apache-2.0"
documentation = "https://docs.rs/bevy_woff"
readme = "README.md"
homepage = "https://github.com/logankaser/bevy_woff"
repository = "https://github.com/logankaser/bevy_woff"
categories = ["game-engines", "graphics"]
include = ["Cargo.toml", "src", "README.md", "LICENSE-MIT", "LICENSE-APACHE"]

[lib]

[dependencies]
bevy_asset = "0.19"
bevy_text = "0.19"
bevy_app = "0.19"
bevy_reflect = "0.19"
thiserror = "2"
wuff = { version = "0.2", default-features = false }

[features]
default = ["woff2"]
woff1 = ["wuff/z"]
woff2 = ["wuff/brotli"]

[[example]]
name = "simple"
required-features = ["woff1", "woff2"]

[dev-dependencies]
bevy = { version = "0.19", default-features = false, features = ["2d", "webgpu", "ui"] }
